language: ruby
sudo: false
rvm:
- 2.2.4
env:
  # No OAuth2 Client ID / IP range limited
  GOOGLE_CALENDAR_API_KEY=AIzaSyBua5ystvigElyCGBeJQ-lvXnLAal5k_jw
install:
- gem install bundler
- bundle install
script:
- bundle exec rake spec
